### ISSUE TITLE
HW2

### ISSUE THREAD

**Issue by alevtina99** [alevtina99/r-course#2]
Solved HW#2

**Comment by AntonZamyatin** [comment]
Hello,
The task was to explicitly calculate the chances to win. Not printing "?%"
Maybe it is simpler to understand and you could each round print chances to lose in the next round
Cant count this HW without probability calculation. Another code seems good.

**Comment by AntonZamyatin** [comment]
another thing:
you should not use for cycles to take a sum in R
`sum()` function can do it for you. It summarize different types of objects inside and of course numeric vectors.

Using FOR cycles in R is not a good strategy. You can always find suitable function.

**Comment by alevtina99** [comment]
Thank you, will try to correct everything

вт, 19 апр. 2022 г., 19:02 Anton Zamyatin ***@***.***>:

**Comment by AntonZamyatin** [comment]
#3
